name: Code check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8
        run: flake8 .

  run_tests:
    runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

        - name: Install Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.10

        - name: Install requirements
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run tests
          run: python -B -m pytest